services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      args:
        user: trackly
        uid: 1000
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - backend
    networks:
      - api

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      args:
        user: trackly
        uid: 1000
      context: .
      dockerfile: ./.docker/php/Dockerfile
    environment:
      APP_NAME: Trackly
    tty: true
    volumes:
      - ./backend:/var/www/html
    networks:
      - api

  # redis:
  #   container_name: redis
  #   image: redis:alpine
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - backend

  node:
    container_name: node
    restart: unless-stopped
    build:
      args:
        user: node
        uid: 1000
      context: .
      dockerfile: ./.docker/node/Dockerfile
    ports:
      - "5173:5173"
    tty: true
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - nginx
    networks:
      - api

networks:
  api:
    driver: bridge